### ISSUE TITLE
Terminal color changes to black

### ISSUE THREAD

**Issue by kishy-codes** [yannjor/krabby#14]
![Screenshot_20231008_014434](https://github.com/yannjor/krabby/assets/106916795/8a4ae7f9-1cd7-40f6-b485-685c6f11b3ac)

OS: Arch Linux
DE: Plasma
Terminal: Konsole
Shell: bash
Install Source : AUR
Krabby Version: 0.1.7

**Comment by kishy-codes** [comment]
i have personally switched over to `fish` shell and i cannot reproduce it, and is henceforth not relevant to me anymore.

**Comment by yannjor** [comment]
interesting, seems to only happen on bash :thinking:

**Comment by unit537** [comment]
Confirming this affects bash. I took a cursory look over the repo and I believe the issue is with the individual colorscripts files, specifically the last [ANSI escape code](https://en.wikipedia.org/wiki/ANSI_escape_code#3-bit_and_4-bit) in each file.

The Inkay, Honchkrow, and Whirlipede files end with "[0m", which is the code for reset/no color, but most of the colorsprite files end with the last ANSI escape code needed to color the last 'pixel' in the sprite, which seems to almost always be black for the border around the sprite.

I can confirm that Inkay, Honchkrow, and Whirlipede always leave my terminal foreground color intact. For getting random sprites, running `krabby random; echo -e '\033[0m'` always results in the foreground color being reset correctly. A quick fix might be appending "[0m" to the string you;re getting from the colorsprites files.

Arch/Kitty/Bash, installed from [AUR](https://aur.archlinux.org/packages/krabby-bin), Version 0.1.7
