### ISSUE TITLE
possibility to pipe to neofetch?

### ISSUE THREAD

**Issue by Blakeinstein** [yannjor/krabby#6]
Is there an option to get this output to neofetch? (using image_source command output)

**Comment by yannjor** [comment]
Interesting idea. I couldn't get this to work properly however. The pokemon art is printed but seems to take so much space that the neofetch output disappears.

Example with `neofetch --ascii "$(krabby random --no-title)"`

![screenshot](https://user-images.githubusercontent.com/43335028/185782325-d149f331-117d-4ff8-af5b-c94378418b45.png)
I think it may be because neofetch expects a certain [ascii file format](https://github.com/dylanaraps/neofetch/wiki/Custom-Ascii-art-file-format).

If you have any idea how to work around this I would be interested.

**Comment by Blakeinstein** [comment]
This is actually apparently blocked on https://github.com/dylanaraps/neofetch/issues/1303

maybe we can get this to be an image, copy over to a buffer then use an image backend like kitty to display the image?

**Comment by yannjor** [comment]
Oh nice catch! Seems like there is an open [pull request ](https://github.com/dylanaraps/neofetch/pull/1543) that fixes this but it hasn't been been merged. Overall it looks like the neofetch repo is quite inactive.

I tried the same command with the fix from the PR and it seems to work. One work around for now could thus be to use a more up to date fork of neofetch, for example [hyfetch](https://github.com/hykilpikonna/hyfetch).

> maybe we can get this to be an image, copy over to a buffer then use an image backend like kitty to display the image?

Yeah I guess that would work too but it seems like quite a lot of trouble for what it's worth. We would then need all of the sprites as images which would use up quite a lot of space. Or maybe use some other program in between to convert the output to an image, but I don't know how viable this is.

**Comment by Blakeinstein** [comment]
> One work around for now could thus be to use a more up to date fork of neofetch, for example [hyfetch](https://github.com/hykilpikonna/hyfetch).
> 
This actually is indeed the solution. I setup my config to use pokemon-colorscripts (because that is what I was trying out, and seems to be the fastest atm) and got great results
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/42214598/185786286-5d4c2ae2-42c1-43e8-9315-e0865436ad84.png">
